# -*- mode: python -*-

Import('env')

objects = []
objects += env.Object('cpuid.c')
objects += env.Object('kmain.c')
objects += env.Object('kprintf.c')
objects += env.Object('panic.c')
objects += env.Object('process.c')
objects += env.Object('screen.c')
objects += env.Object('gdt.c')
objects += env.Object('interrupt.c')
objects += env.Object('task.c')
objects += env.SConscript('intr/SConscript', exports=['env'])

Return('objects')
