# -*- mode: python -*-
Import('env')

objects = env.Object([
    'gdt.S',
    'idt.S',
    'isr.S',
    'pagedir.S',
    'ring3.S',
])

# The linker script includes boot.S explicitly.  Don't include it in objects.
boot = env.Object('boot.S')

Return(['objects', 'boot'])
