# -*- mode: python -*-

Import('env')

objects = []
objects += env.Object('cpuid.c')
objects += env.Object('kmain.c')
objects += env.Object('kprintf.c')
objects += env.Object('panic.c')
objects += env.Object('process.c')
objects += env.Object('screen.c')

Return('objects')
