# -*- mode: python -*-
Import('env')

# Compile the sources.
objects = env.Object([
    'address_space.c',
    'common.c',
    'heap.c',
    'linear.c',
    'physical.c',
    'sbrk.c',
])

Return(['objects'])
