# -*- mode: python -*-
Import(['env', 'iso'])

# Create the bochs config.
bochs = env.Sed(
    'bochs.cfg',
    'bochs.cfg.in',
    PATTERN="s:@@ISOPATH@@:${ISOPATH.abspath}:g",
    ISOPATH=iso[0],
)

Return('bochs')
